### Register new user
#POST https://shebogholo.com/springboot1/api/v1/auth/register
POST http://localhost:150/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "user6",
  "lastName": "user6",
  "email": "user@gmail",
  "password": "A#1"
}


### Login
#POST https://shebogholo.com/springboot1/api/v1/auth/login
POST http://localhost:150/api/v1/auth/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "user1"
}


### Get all users
#GET https://shebogholo.com/springboot1/api/v1/users
GET http://localhost:150/api/v1/users
Accept: application/json


### Get user by Id
GET https://shebogholo.com/springboot1/api/v1/users/1
Accept: application/json


### Delete user by Id
DELETE https://shebogholo.com/springboot1/api/v1/users/1001
Accept: application/json


### Update user details
PUT https://shebogholo.com/springboot1/api/v1/users/1
Content-Type: application/json

{
  "firstName": "",
  "lastName": "3",
  "email": "g@gmail.com"
}