version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: backend
    image: backend:1.0
    restart: unless-stopped
    ports:
      - "150:150"
    volumes:
      - ./:/app
    depends_on:
      - database
    networks:
      - dev

  database:
    image: mariadb:10.8
    container_name: database
    restart: always
    ports:
      - "3308:3308"
    environment:
      MARIADB_DATABASE: docker
      MARIADB_USER: docker
      MARIADB_PASSWORD: docker
      MARIADB_ROOT_PASSWORD: docker
    volumes:
      - .data:/var/lib/mysql
      - .docker/config.cnf:/etc/mysql/conf.d/config.cnf
    networks:
      - dev

networks:
  dev:
    driver: bridge